### ISSUE TITLE
Bug - ControlHub Cannot Persist Egress Field in NetworkPolicy

### ISSUE THREAD

**Issue by touch4** [beclab/Olares#1453]
When editing a `NetworkPolicy` in the `homeassistant-touch4benny` namespace using the ControlHub interface, the UI accepts the changes (returns HTTP 200), but the actual resource is not updated.

I attempted to add the following `egress` section to the existing policy:

```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: app-np
  namespace: homeassistant-touch4benny
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              bytetrade.io/ns-owner: touch4benny
              bytetrade.io/ns-type: user-internal
        - namespaceSelector:
            matchLabels:
              bytetrade.io/ns-type: system
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: homeassistant-touch4benny
  egress:
    - to:
        - ipBlock:
            cidr: 192.168.1.141/32
      ports:
        - protocol: TCP
          port: 7897
  policyTypes:
    - Ingress
    - Egress

```
**Steps to reproduce:**

- Navigate to ControlHub -> Resources -> Network Policies
- Edit a policy YAML
- Add a valid egress section
- Click OK to confirm
- Check via kubectl get networkpolicy app-np -n homeassistant-touch4benny -o yaml
![Image](https://github.com/user-attachments/assets/96e3fb70-bb68-4fb0-8421-a84b8071d662)
**Expected Result:**
The egress field should be added to the resource.

**Actual Result:**
The resource remains unchanged — only ingress is present.

**Verification:**

- The request returns HTTP 200
- generation increments (confirming update triggered)
- YAML is valid per K8s spec
- kubectl apply works as expected

**Environment:**

- Olares version: 1.11.7
- OS: Ubuntu 22.04
- Arch: AMD64

Please confirm if this is an intentional restriction or a bug.
